apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: stocks-app
spec:
  type: NodePort # Allows external access to the cluster
  selector:
    app: nginx
  ports:
    - port: 80 #  Internal service port
      targetPort: 80 # Port that the container listens on
      nodePort: 31322 # External port for outside access (must be between 30000-32767)