# Manages the stocks application pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks
  namespace: stocks-app
spec:
  replicas: 2
  selector: # How the deployment finds which pods to manage
    matchLabels:
      app: stocks
  template: # The pod template specification
    metadata:
      labels:
        app: stocks
    spec:
      containers:
        - name: stocks
          image: stocks:latest
          imagePullPolicy: IfNotPresent # Use local image if available
          ports:
            - containerPort: 8000
          env: # Environment variable for flask
            - name: COLLECTION_NAME
              value: "collection1"
            - name: PORT
              value: "8000"