# Manage capital-gains service pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capital-gains
  namespace: stocks-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capital-gains
  template:
    metadata:
      labels:
        app: capital-gains
    spec:
      containers:
        - name: capital-gains
          image: capital-gains:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"