# Manages mongoDB pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: stocks-app
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:             # Mount persistent volume to store data
            - name: mongo-storage
              mountPath: /data/db   # MongoDB data directory
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc    # Name of the persistent volume claim