# Defines storage resource in the cluster
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: stocks-app
spec:
  capacity:
    storage: 1Gi        # Storage size
  accessModes:
    - ReadWriteOnce     # Can be mounted by one node for read/write
  hostPath:
    path: "/data/mongo" # Path on the host machine